#+TITLE: Kopie bezpieczestwa
#+SUBTITLE: Projektowanie system贸w bezpieczestwa
#+AUTHOR: Patryk Gronkiewicz 164157, Piotr Krawiec 164165
#+EMAIL: 164157@stud.prz.edu.pl, 164165@stud.prz.edu.pl
#+OPTIONS: toc:nil
#+LANGUAGE: pl

* Wybrane programy
** Rsync + tar
Jest to najprostsza opcja dostpna na praktycznie ka偶dym urzdzeniu z Linuxem. Rozwizanie to skada si w rzeczywistoci z dw贸ch program贸w - =rsync= oraz =tar=. Pierwszy z nich su偶y do kopiowania plik贸w lokalnie oraz na serwery zdalne, natomiast drugi generuje pojedynczy plik z naszego backupu. =tar= pozwala tak偶e na zmniejszenie rozmiaru kopii dziki wykorzystaniu kompresji.

W naszym przypadku przydatne okazao si te偶 polecenie =date=, kt贸re posu偶yo do nadawania unikalnych nazw kolejnym kopiom zapasowym. Dodatkowo zastosowano =cron=-a, kt贸ry pozwoli nam na zaplanowanie wykonywania kopii.
** Duplicati
W naszym zestawie rozwiza jest to najbardziej multiplatformowe i proste do u偶ycia rozwizanie - jest proste do ustawienia zar贸wno na Windowsie, Linuxie, jak i macOS. Po zainstalowaniu go mo偶emy zarzdza wszystkimi jego ustawieniami z pomoc interfejsu przegldarkowego. Jako jedyne niestety nie ma opcji ustawiania z pomoc linii komend, co mo偶na rozwiza z pomoc zewntrznych pakiet贸w dostpnych np. w =pip=-ie.
** Restic
Rozwizanie najbardziej rozbudowane, lecz wymagajce wicej dowiadczenia w konfiguracji. Pozwala na stosunkowo proste skonfigurowanie retencji, poczenia do mniej typowych chmur takich jak S3, lecz nie uruchamia si automatycznie. Do odpowiedniego dziaania wymagane jest, aby u偶y planowania backup贸w przez CRON lub =systemd-timers=.

Tw贸rcy twierdz, 偶e jest:
+ prosty w obsudze
+ Efektywny
+ Bezpieczny
+ Weryfikowalny
+ Wolny jak w wolnoci[fn:freedom]
[fn:freedom] (en. /Free as in freedom/ - Richard Matthew Stallman) - dotyczy wolnociowego podejcia do oprogramowania

* Spos贸b dziaania
** Rsync + tar
** Duplicati
** Restic
Restic dziaa na zasadzie kopii przyrostowych - dziki temu jest zdolny do tworzenia stosunkowo maych kopii nawet przy du偶ych ilociach danych. Pozwala tak偶e na atwe przywr贸cenie kopii przez interfejs terminala. Jego dziaanie jest analogiczne do podmontowania np. pendrive.

Kopie zapasowe prowadzone przez Restica mo偶na bardzo prosto zaszyfrowa, jak i wysya na r贸偶ne rodzaje pamici sieciowych - od S3, przez SSHFS i WebDav a偶 po rozwizania typowo konsumenckie jak Google Drive, Mega czy OneDrive. W przypadku czci integracji wymagane jest u偶ycie Rclone, kt贸ry jest interfejsem do poczenia si z dan chmur. Bez najmniejszego problemu jest tak偶e dostpny backup lokalny, kt贸ry tworzony jest w niemal identyczny spos贸b jak ten chmurowy.

Ka偶da kopia zapasowa ma swoje repozytorium - miejsce, gdzie pliki odpowiadajce za kopi s trzymane. Jest to miejsce, kt贸rego nie chcemy straci (ale i tak prawdopowodobnie mamy inny backup, jeli trzymamy si zasad ).
* Retencja
** Rsync + tar
** Duplicati
** Restic
Retencj w Resticu mo偶na bardzo atwo skonfigurowa. Standardowo parametry do niej s podawane podczas wywoania komendy. Tymi argumentami s:
+ =--keep-daily n=
+ =--keep-weekly n=
+ =--keep-monthly n=
+ =--keep-yearly n=
Opisuj ile kopii z danego okresu mamy minimalnie trzyma. Dla np. =--keep-daily 3= bdziemy zawsze mieli ostatnie 3 kopie z danego dnia. Jeli np. w rod zrobimy cztery kopie numerowane chronologicznie od najstarszych - $A$, $B$, $C$ i $D$ - przy takim ustawieniu bdziemy mieli dostp tylko do kopii $B$, $C$ i $D$. Analogicznie dziaa to dla pozostaych argument贸w, kt贸re mo偶emy doda przy wywoaniu funkcji.
* Typy kopii
** Rsync + tar
** Duplicati
** Restic
Jedyn opcj w tym wypadku jest kopia pena podczas inicjalizacji repozytorium, a nastpnie kopie przyrostowe. Pozwala to na "cofnicie si w czasie" o niemal dowolne okno, poniewa偶 mao prawdopodobne jest, 偶e za rok bdziemy potrzebowali kopii z dokadnoci co do dnia.
* Chmura
** Rsync + tar
** Duplicati
** Restic
Restic ma bardzo rozbudowan integracj z chmur - zar贸wno bezporedni, jak i z pomoc narzdzi takich jak rclone. Najprociej integruje si z /object storage/[fn:object_storage]. S to chmury nakierowane na trzymanie wielu maych plik贸w.
[fn:object_storage] - przestrze obiektowa, pozwala na proste trzymanie wielu maych plik贸w i jest wanie w tym celu zoptymalizowane. ,,Klasyczne'' chmury, kt贸re bezporednio udostpniaj dysk nazywane s /block storage/.

Autorzy chwal si natywnym wsparciem dla kilkunastu r贸偶nych chmur, kt贸re mo偶na podzieli na trzy r贸偶ne kategorie:
1. Backup lokalny - dziaa na dysku podczonym do komputera
2. Backup do block storage - Autorzy dostarczaj obsug protokou SFTP (/SSH File Transfer Protocol/), a tak偶e wasny serwer obsugujcy HTTP(S).
3. Backup do object storage - wspierane jest wiele najbardziej popularnych chmur takich jak AWS S3, Backblaze B2, Azure Blob Storage, Wasabi, a tak偶e opcje selfhosted w postaci Minio i OpenStack Swift.

Dodatkowe opcje dostarcza Rclone, kt贸ry pozwala zamontowa nam ponad 50 r贸偶nych chmur, a co za tym idzie istotnie rozszerzy funkcjonalno naszego rozwizania. Dziki cisej integracji nie ma potrzeby podmontowywania danej chmury pod folder, co dziaa na nasz korzy ze wzgldu na jeszcze lepsze zabezpieczenie przed Ransomware.
