#+TITLE: Kopie bezpieczestwa
#+SUBTITLE: Projektowanie system贸w bezpieczestwa
#+AUTHOR: Patryk Gronkiewicz 164157, Piotr Krawiec 164165
#+EMAIL: 164157@stud.prz.edu.pl, 164165@stud.prz.edu.pl
#+OPTIONS: toc:nil
#+LANGUAGE: pl

* Wybrane programy
** Rsync + tar
Jest to najprostsza opcja dostpna na praktycznie ka偶dym urzdzeniu z Linuxem. Rozwizanie to skada si w rzeczywistoci z dw贸ch program贸w - =rsync= oraz =tar=. Pierwszy z nich su偶y do kopiowania plik贸w lokalnie oraz na serwery zdalne, natomiast drugi generuje pojedynczy plik z naszego backupu. =tar= pozwala tak偶e na zmniejszenie rozmiaru kopii dziki wykorzystaniu kompresji.

W naszym przypadku przydatne okazao si te偶 polecenie =date=, kt贸re posu偶yo do nadawania unikalnych nazw kolejnym kopiom zapasowym. Dodatkowo zastosowano =cron=-a, kt贸ry pozwoli nam na zaplanowanie wykonywania kopii.
** Duplicati
W naszym zestawie rozwiza jest to najbardziej multiplatformowe i proste do u偶ycia rozwizanie - jest proste do ustawienia zar贸wno na Windowsie, Linuxie, jak i macOS. Po zainstalowaniu go mo偶emy zarzdza wszystkimi jego ustawieniami z pomoc interfejsu przegldarkowego. Jako jedyne niestety nie ma opcji ustawiania z pomoc linii komend, co mo偶na rozwiza z pomoc zewntrznych pakiet贸w dostpnych np. w =pip=-ie.
** Restic
Rozwizanie najbardziej rozbudowane, lecz wymagajce wicej dowiadczenia w konfiguracji. Pozwala na stosunkowo proste skonfigurowanie retencji, poczenia do mniej typowych chmur takich jak S3, lecz nie uruchamia si automatycznie. Do odpowiedniego dziaania wymagane jest, aby u偶y planowania backup贸w przez CRON lub =systemd-timers=.

Tw贸rcy twierdz, 偶e jest:
+ prosty w obsudze
+ Efektywny
+ Bezpieczny
+ Weryfikowalny
+ Wolny jak w wolnoci[fn:freedom]
[fn:freedom] (en. /Free as in freedom/ - Richard Matthew Stallman) - dotyczy wolnociowego podejcia do oprogramowania

* Spos贸b dziaania
** Rsync + tar
** Duplicati
** Restic
Restic dziaa na zasadzie kopii przyrostowych - dziki temu jest zdolny do tworzenia stosunkowo maych kopii nawet przy du偶ych ilociach danych. Pozwala tak偶e na atwe przywr贸cenie kopii przez interfejs terminala. Jego dziaanie jest analogiczne do podmontowania np. pendrive.

Kopie zapasowe prowadzone przez Restica mo偶na bardzo prosto zaszyfrowa, jak i wysya na r贸偶ne rodzaje pamici sieciowych - od S3, przez SSHFS i WebDav a偶 po rozwizania typowo konsumenckie jak Google Drive, Mega czy OneDrive. W przypadku czci integracji wymagane jest u偶ycie Rclone, kt贸ry jest interfejsem do poczenia si z dan chmur. Bez najmniejszego problemu jest tak偶e dostpny backup lokalny, kt贸ry tworzony jest w niemal identyczny spos贸b jak ten chmurowy.

Ka偶da kopia zapasowa ma swoje repozytorium - miejsce, gdzie pliki odpowiadajce za kopi s trzymane. Jest to miejsce, kt贸rego nie chcemy straci (ale i tak prawdopowodobnie mamy inny backup, jeli trzymamy si zasad ).
* Retencja
** Rsync + tar
** Duplicati
** Restic
* Typy kopii
** Rsync + tar
** Duplicati
** Restic
* Chmura
** Rsync + tar
** Duplicati
** Restic
